### PR TITLE
feat: add Ukrainian (uk) translation

### PR DESCRIPTION
**Pull request by Plazmius**
This PR adds support for the Ukrainian keyboard layout and Ukrainian translation of the website. The phonetic model was generated using a fiction txt dataset from https://lang.org.ua/en/ubertext/. Translations were generated using Google Translate and corrected by me, although I did not have much time to correct everything.

### CODE REVIEW

**Comment by aradzie** [comment]
Thanks for your PR!

**Comment by Ravikisha** [comment]
I have a question for learning purposes for @Plazmius , How you translate the entire `messages/uk.json` and `translations/uk.json`. Thanks in advance and good work.

**Comment by Ravikisha** [comment]
Thanks for help

**Comment by Plazmius** [comment]
@Ravikisha in case you were asking, how I actually translated so much text, I have extracted all of the messages in simple txt file, then threw them into Google Translate, and then composed them once again into JSON after quick manual validation, keeping order.

**Comment by Ravikisha** [comment]
Nice! Thanks for help

**Comment by Plazmius** [comment]
@Ravikisha 
I have generated the phonetic model using this tool - https://github.com/aradzie/phoneticmodel
You can add the alphabet for your language to this file (if it's not already there) - https://github.com/aradzie/phoneticmodel/blob/master/src/main/java/com/keybr/phoneticmodel/Language.java
And then compile and run using Maven

To generate a phonetic model, you need a large text corpus in a plain text (txt) file. Usually, you can find one if you search for NLP datasets on the internet, just make sure it has acceptable quality. Also, cut the txt file to a maximum `50mb`, as the bigger size caused the tool to run out of memory in my case

**Comment by aradzie** [comment]
> I am trying to add a new language. Help me: How to generate the phonetic model and what is blacklist-lang.json file. Sorry for disturb but i want this for my learning Thanks in Advance.


First and foremost, there are two thing that you can do independently, one at a time:

1. Translate the user interface to your language by editing  JSON files, and
2. Add a phonetic model of your language to generate texts.

Both of these can be done by copying and modifying the existing code.

I'll leave it as a homework to discover the details, but in general the process is as follow.

To translate the UI, take the [English messages JSON file](https://github.com/aradzie/keybr.com/blob/master/packages/keybr-intl/translations/en.json), make your copy, translate it and add to the project. Then you need to run `node scripts/gen-translations.js` Study the source code of this script. Read about [react-intl](https://formatjs.io/docs/tooling/cli/) 

To add a phonetic model for your language, you need to make a binary file with the language data. Use this tool https://github.com/aradzie/phoneticmodel
It's written in Java and you need to be able to modify and compile it yourself. You also need a large piece of raw text in your language. Then you feed this text to the tool and it will generate a binary file for you.

PS
I need to write a guide on how to help with translations and languages.
You can reach me on Discort so that we can chat in real time.

**Pull request merged**
