### PR TITLE
feat: add german neo 2 and bone layouts

### PR DESCRIPTION
**Pull request by lwalthert**
Neo and Bone are two ergonomic keyboard layouts with the german Language in mind. They live on the website [neo-layout.org](https://neo-layout.org). This commit adds the required configurations to support them in keybr.com. This was also requested in issue #93  by another user.

Please get back to me if you want any changes done.

### CODE REVIEW

**Comment by aradzie** [comment]
That is an awesome PR, thanks a lot!

**Comment by aradzie** [comment]
I've updated the website with your changes, enjoy!

**Comment by Finnitio** [comment]
Would it be possible to also add CMOS and XOY Layouts?
image
image
Both perform very well on [https://dariogoetz.github.io/keyboard_layout_optimizer/](https://dariogoetz.github.io/keyboard_layout_optimizer/) For a german and englisch mix. Would be greatly appreciated!

**Comment by aradzie** [comment]
@Finnitio Can you please give me a machine readable layout definition? I mean a JSON or  XML file, a keyboard layout creator file, whatever.

**Comment by Finnitio** [comment]
[cmos keyboard-layout.json](https://github.com/user-attachments/files/17509264/cmos.keyboard-layout.json)
Would this work for you?

**Comment by Finnitio** [comment]
[layout_de_cmos.json](https://github.com/user-attachments/files/17519003/layout_de_cmos.json)
I habe modified the ts file from the pr.

**Comment by Finnitio** [comment]
Wow that was fast! Yeah the name is a little weird. It has not been published on any website like the neo family. But by the metrics of the analyiser that I linked above it is by far the best performing. So I am keen to learn it, since a layout that performs well on German and english is what i need ;). Thanks a lot!

**Comment by aradzie** [comment]
I think it's worth adding a custom layout designer. A few people have already requested this feature. I made a quick prototype and it seem to be working.

image

**Comment by Finnitio** [comment]
That would be awsome!

**Pull request merged**
