### PR TITLE
Add new Q words (and a few P words just because!)

### PR DESCRIPTION
**Pull request by saltedlolly**
I have tried to ensure that every other letter shows up when targeting Q. I have succeed for every word except W though some letters are very rare:

- Q and G we have ‘squiggle' and 'squiggling' ‘quagmire’ and ‘liquefying’
- Q and J we have ‘jaquard’ only.  (This was the only word I could find - google it.)
- Q and V we have ‘quiver’, ‘quaver’ and’ ‘quantitative’.  
- Q and W I can’t find any words.
- Q and X we have 'quixotic’, ‘exquisite’  and 'equinox' 
- Q and Z we have 'quiz’, ‘quizzical’ and 'quartz'.  

Only W is not used when typing Q with this new list. It would be good to add some fake words for Q and W? How about ‘quawl’ and ‘qwetch’? 

I don't how fake words are generated. Is there a separate list somewhere or are they generated on the fly?

### CODE REVIEW

**Comment by aradzie** [comment]
This file is generated and will be overwritten on next compile.
However, let merge it anyway until I come up with a better solution.

**Comment by aradzie** [comment]
And yes, thanks for your work!

**Comment by aradzie** [comment]
[English word frequency dictionary](https://github.com/aradzie/keybr.com/blob/master/packages/keybr-generators/dictionary/dictionary-en.csv.gz) is the original file from which the word list is built.

It is a gzipped CSV file, we keep it compressed because it usually changes as a whole and the git diff command reports one giant delta. And to save space in the repository.

**Comment by saltedlolly** [comment]
Ah sorry, my mistake.  Shall i update that file with the new words?

**Comment by aradzie** [comment]
I can fix that dictionary file myself.

**Comment by saltedlolly** [comment]
Ok. 

I was thinking of helping to submit some more words for the other letters. what is the best to do that? Is it better to edit the CSV files directly in future? If so, what is the numerical value in the second column?

Also, what about fake words - is there a seperate list for them? It would be good to add a few fake words for Q and W since no real words exist that i could find.

**Comment by aradzie** [comment]
> Ok.
> 
> I was thinking of helping to submit some more words for the other letters. what is the best to do that? Is it better to edit the CSV files directly in future? If so, what is the numerical value in the second column?
> 
> Also, what about fake words - is there a seperate list for them? It would be good to add a few fake words for Q and W since no real words exist that i could find.

I have already done it in 8271432a23b3df1ff122db7efdb8d2438d9595a2. I expanded the English dictionary to 10000 words, and added some of the Q words listed by you.

The list of words with Q: quite, squire, acquainted, question, acquaintance, consequence, equal, frequently, quiet, quality, quit, equally, quarter, quickly, inquired, quietly, quick, frequent, questions, quantity, required, request, consequently, consequences, qualities, require, inquiry, square, quest, inquire, quarrel, requires, inquiries, enquire, quitting, quarters, subsequent, tranquil, acquired, tranquillity, adequate, enquiry, exquisite, masquerade, quoth, conquered, qualified, conquest, qualifications, questioned, earthquake, frequented, eloquence, enquired, unacquainted, inquiring, antique, quivering, relinquish, unequal, acquainting, acquitted, conquer, conqueror, enquiring, queen, squares, acquiesced, acquit, antiquity, equality, equivalent, liquid, oblique, obliquely, quivered, sequel, acquaintances, equinox, equipage, grotesque, quarrelled, quoted, requested, requiring, squeeze, tranquilly, acquire, adequately, eloquent, quadrant, quaint, quarrelling, quickness, requisite, squires, banquet, bequeathed, conquests, disquiet, equalled, equipped, exquisitely, inadequate, liquors, picturesque, piqued, quartered, quilt, relinquished, squeezed, squeezing, subsequently, acquiescence, consequent, equals, equator, equatorial, iniquity, inquisitive, piquant, qualify, quarrels, queens, questioning, quiescence, quieted, quieter, quiver, quote, acquiesce, acquisition, acquittal, aqua, aquatic, barbeque, bouquet, boutique, cheque, colloquial, consequential, coquetry, critique, disqualification, disqualify, earthquakes, equate, equation, equilibrium, equip, equipment, equity, esquire, frequency, harlequin, inequality, infrequent, inquest, jacquard, liquefy, liquefying, liquor, liquorice, loquacious, mannequin, opaque, prerequisite, quack, quadruped, quadruple, quagmire, quake, qualifier, qualm, quantification, quantify, quantitative, quantum, quark, quarterly, quartet, quartz, quasar, quaver, quay, queasy, quell, quench, query, questionnaire, queue, quibble, quintessential, quip, quirk, quirky, quixotic, quiz, quorum, quota, quotation, quotient, reacquire, requiem, sequence, sequin, squeamish, squiggle, squiggling, technique, torque, ubiquitous, ubiquity, unique

**Pull request merged**
