### PR TITLE
[FIX] Typo on words-es

### PR DESCRIPTION
**Pull request by pinarruiz**
I think that these words are typos:

`dilettante`: means nothing -> `diletante`: [RAE](https://dle.rae.es/diletante)
`docientos`: means nothing -> `doscientos`: Number 200

It bugs my brain when i encounter them, especially `docientos`.
I dont know if it is intentional or not, if so, just close the PR.

Fantasatic app to learn touch typing btw :smile:

Edit: Fix my own typos :expressionless:

### CODE REVIEW

**Comment by aradzie** [comment]
Hi, thanks for your PR!

The file that you changes is automatically generated, it should not be changed by hand.

It is a know issue that it is [hard to contribute](https://github.com/aradzie/keybr.com/issues/129) to the project, and I definitely should update the [docs](https://github.com/aradzie/keybr.com/blob/master/docs/custom_language.md).

In the mean time, let me explain in this comment how we add/update languages.

It starts with a good word frequency dictionary. A word frequency dictionary is a CSV file with a list of `word,count` pairs. We keep these dictionaries in the [generators](https://github.com/aradzie/keybr.com/tree/master/packages/keybr-generators/dictionary) package. The dictionaries are gzip-ed because if we rebuild them, then every count changes, resulting in a diff which replaces every line in a file.

So the original [dictionary-es.csv](https://github.com/aradzie/keybr.com/blob/master/packages/keybr-generators/dictionary/dictionary-es.csv.gz) should be fixed. Then there is a special [script](https://github.com/aradzie/keybr.com/blob/master/packages/keybr-generators/lib/generate-languages.ts) which reads the dictionary and updates the file that you fixed in your PR.

However, the best way is to fix the original corpus from which the Spanish word frequency dictionary is built.

We keep the development of these dictionaries in a [separate repository](https://github.com/aradzie/keybr.com-corpus). It is a collection of tool for parsing a corpus of text. Now, getting a good corpus is a tricky problem, and a few options are available. [The Spanish language corpus](https://github.com/aradzie/keybr.com-corpus/blob/master/lang-es/corpus.txt) I created myself from a few classic novellas, such as Don Quijote. The mistakes that you have fixed are in that corpus.

However, for most other languages we take corpora from [the Open Subtitles database](https://opus.nlpl.eu/OpenSubtitles/en&es/v2018/OpenSubtitles). These corpora are usually much larger, they contain contemporary, simple,  ever day language. However, they also contain a lot of profane, obscene, vulgar words and must be rewired and cesnored manually by native speakers.

Sounds complicated? Here's TLDR:

1) You can let me fix everything by myself. I have seen you changes, I can update the original corpus and rebuild the Spanish word frequency dictionary.

2) You can create a PR against the [original corpus](https://github.com/aradzie/keybr.com-corpus/blob/master/lang-es/corpus.txt), then I'll do the rest.

3) The best option. We will start from scratch and rebuild the Spanish dictionary from the movie subtitles. I will do all the heavy lifting, then send you a link to a spreadsheet with the dictionary. You will review that spreadsheet and remove all bad words from it. Then I'll do the rest and update keybr with the reviewed dictionary.

Sounds good? Which option do you chose?

**Comment by pinarruiz** [comment]
Im gonna give it a try and let you know :smile:

**Comment by pinarruiz** [comment]
Just created https://github.com/aradzie/keybr.com-corpus/pull/1 I am closing this one as there is no need for it anymore. Anyways, if you wanna go for option 3 i will be happy to help with that :wink: (just tag me on the PR, or contact me on my commiter email), but wanted to remove the typo for time being.

**Comment by aradzie** [comment]
Here is [the spreadsheet](https://docs.google.com/spreadsheets/d/1ouf1ceQUT-jOKEs4Mv8UaljfOnPXO_cjqj83HNb4lzw/edit?usp=sharing) that I built it from movie subtitles.

When we scan a corpus, first we pass the scanned words through an [Aspell](http://aspell.net/) dictionary to exclude unknown words. Then we pass the words through a custom blacklist filter to remove known bad words. I did my own research and found a list of [bad Spanish words](https://github.com/aradzie/keybr.com-corpus/blob/master/lang-es/blacklist.txt) on the internet. However, this list might be incomplete. So, can you please review the first 2-3 thousand words in the spreadsheet and remove bad words that are still there?

Thanks!

**Comment by pinarruiz** [comment]
Sure, give me some time and ill let you know what i find :wink:

**Comment by pinarruiz** [comment]
Red, Yellow and Blue make reference to the background of the row, did not wanna erase rows just in case.
The format is `row number` `finding`: Explanation.
For the first 3000 rows:

Would remove (Red background):
- `406` `e`: The reason being it would not make much sense to have it there, ists just the letter e. In spanish we use it to replace the "y" when the next word starts with an i, for example: `Antonio y Isabel` would be `Antonio e Isabel`.
- `2394` `u`: Reason similar to `y`, example: `herramientas o otros` would be `herramientas u otros`.

Maybe not remove, but want to discuss (Yellow background):
- `2342` `suicidio`: This is the translation for the word suicide, while i personally don't mind about it i know it might be sensible for some people.

Bad words (Blue background):
- `2670` `tontos`: Soft insult but [Bad Spanish words #L228](https://github.com/aradzie/keybr.com-corpus/blob/master/lang-es/blacklist.txt#L228) has the singular form.
- `2871` `putas`: [Bad Spanish words #L210](https://github.com/aradzie/keybr.com-corpus/blob/master/lang-es/blacklist.txt#L210) has the singular form.

**Comment by aradzie** [comment]
Thanks, I've updated the Spanish dictionary. I will update the website a bit later.

**Pull request closed without merging**
