### PR TITLE
Adding Hands Down Promethium

### PR DESCRIPTION
**Pull request by lorantfecske-red61**
Adding Hands Down Promethium layout.

The layout is designed for Matrix/Ortholinear split keyboards with thumbcluster, so the R is missing.

More about the layout: 
https://www.reddit.com/r/KeyboardLayouts/comments/1g66ivi/hands_down_promethium_snth_meets_hd_silverengram/

Screenshot 2024-11-22 at 14 18 56

### CODE REVIEW

**Comment by lorantfecske-red61** [comment]
@aradzie that was superquick, thanks :)

**Comment by aradzie** [comment]
Thanks!
I have update the website with your changes.
Indeed, the R is missing

image

What should we do about it, design a new geometry? Update the existing martrix geometry?

**Comment by lorantfecske-red61** [comment]
I think the optimal solution would be to design a new geometry, something like one on the screenshot. On the other hand, split keyboards with thumb clusters seems to have different thumb clusters with different form factor (number of keys, position of keys, size of the keys). The Hands Down Gold, Titanium, Rhodium, Vibranium and Promethium all have 1 letter on the thumb cluster and they all have 4 thumb cluster keys, so I would probably go with 4 thumb keys. 

I'm not sure how much work is to design a new geometry, at this point I'm pretty happy that I can practice even without the r key.

**Comment by f5b7** [comment]
@aradzie I think it's reasonable to update the existing matrix geometry, adding 4 thumb keys. I'd argue that almost all matrix/ortho keyboards today have at least two thumb keys per side. They're also mostly column staggered but that should be okay to ignore.

Also, layouts with a thumb key are gaining popularity, so I think it's worth the effort. Most layouts suggest to use the thumb space key on the side where the/most vowels are and the thumb letter key on the other (consonant) side. The remaining thumb keys are often used as shift (next to the thumb letter) and layer switch. Shift on a thumb instead of pinky is especially helpful to decrease pain/fatigue/RSI.

Source of all my claims: Way too many hours spent on Reddit, Discord and whatnot about alt keyboard layouts.

**Pull request merged**
