### PR TITLE
feat: add Ergo-L layout

### PR DESCRIPTION
**Pull request by c4software**
This PR added support to the Ergo-L layout.

### CODE REVIEW

**Comment by aradzie** [comment]
Awesome!

**Comment by aradzie** [comment]
I'll fix errors myself. Again, thanks for the PR!

**Comment by c4software** [comment]
Oh that was fast. Already on the .xyz I will validate if everything is fine 👍

**Comment by c4software** [comment]
Hi,

It's seems ok 👌

**Pull request merged**
