### PR TITLE
feat(layout): add Erglace French layout

### PR DESCRIPTION
**Pull request by steevelefort**
Hi !
This pull request adds the 'Erglace' French layout to Keybr. It's a wonderful layout with excellent metrics.
For more information about 'Erglace' :
Erglace web site : https://ergol.org/erglace/
Erglace metrics : https://ergol.org/stats/#/erglace/ol50/en+fr
Feel free to get back to me if you have any questions.
Have a good day!

### CODE REVIEW

**Comment by aradzie** [comment]
Thanks!

**Comment by steevelefort** [comment]
We can maybe update "/packages/keybr-keyboard/lib/types.ts" to resolve the test issue ?
image
```ts
export type CodePointDict = {
  readonly [id: KeyId]: readonly [
    a?: CodePoint,
    b?: CodePoint,
    c?: CodePoint,
    d?: CodePoint,
    e?: CodePoint,
  ];
};
```

**Comment by aradzie** [comment]
We only support up to four different key states:

1. no modifier
2. shift
3. altgr
4. shift+altgr

I will fix the compilation errors, don't worry.

**Comment by aradzie** [comment]
I will write a converter from the [kalamine JSON format](https://github.com/OneDeadKey/kalamine) to the internal format. Then I'll pass the [erglace layout](https://github.com/Nuclear-Squid/ergol/blob/main/layouts/erglace.toml) through the converter.

Btw, thanks for showing me the kalamine project, it's cool.

**Comment by steevelefort** [comment]
Erglace (and Ergo-L) uses a dead key to produce accentued french characters (éêèà...). Adding a fifth entry made it works (I don’t know why)
image
The dead key offers these green characters
image

**Pull request merged**
