### PR TITLE
feat: add Canary matrix layout

### PR DESCRIPTION
**Pull request by VictorTennekes**
This PR adds support for the ortho canary layout.

https://github.com/Apsu/Canary

### CODE REVIEW

**Comment by VictorTennekes** [comment]
Not sure where that file went, I'll re-add it.

**Comment by aradzie** [comment]
That's ok. Most of the PR is good, so I can fix it myself. Thank you for your contribution!

**Comment by VictorTennekes** [comment]
Just out of curiosity what's the timeline to see changes reflected on the website?

**Comment by aradzie** [comment]
I have update the website a minute ago. The new layout looks awesome. Enjoy!

**Comment by VictorTennekes** [comment]
Amazing thank you!

**Pull request merged**
